executabil: TemaRC.c processDirectory.c processScn.c loginScreen.c myfind.c processCommand.c quit.c mainScreens.c logout.c errorScreen.c
	gcc -o executabil TemaRC.c processDirectory.c processScn.c loginScreen.c myfind.c processCommand.c quit.c mainScreens.c logout.c errorScreen.c
